name: Upload to Tencent COS
on:
  workflow_run:
    workflows: ["Regenerate PluginMaster"]
    types:
      - completed
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout cn
        uses: actions/checkout@v2
        with:
          ref: cn

      - name: Upload COS
        uses: Bluefissure/tencent-cos-action@v0.1.1
        with:
          args: config -e cos.accelerate.myqcloud.com && delete -r -f / && upload -r ./plugins /plugins && upload ./pluginmaster.json /
          secret_id: ${{ secrets.SECRET_ID }}
          secret_key: ${{ secrets.SECRET_KEY }}
          bucket: ${{ secrets.BUCKET }}
          region: ${{ secrets.REGION }}
          accelerate: true
